/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trashcollector;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

public class Leader_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Leader_Frame
     */
    public Leader_Frame() {
        initComponents();
        loadTrashCollectedData();
        calculateTotalTrashCollected();
        loadLeaderboard();
        setLocationRelativeTo(null);
        
    }
    public class DatabaseConnection {
        public static Connection connect() {
            try {
                // Load the database driver (for MySQL, for example)
                Class.forName("com.mysql.cj.jdbc.Driver");
                // Establish the connection
                return DriverManager.getConnection("jdbc:mysql://localhost:3306/trash_db", "root", "");
            } catch (ClassNotFoundException | SQLException e) {
                e.printStackTrace();
            }
            return null;
        }
    }
    public void loadTrashCollectedData() {
    DefaultTableModel model = (DefaultTableModel) TrashCollectedTable.getModel();
    model.setRowCount(0); // Clear existing data

    try (Connection con = DatabaseConnection.connect();
         Statement stmt = con.createStatement();
         // SQL query updated to exclude users with 'leader' role
         ResultSet rs = stmt.executeQuery("SELECT u.username, tc.collection_date, tc.total_weight " +
                                          "FROM users u " +
                                          "LEFT JOIN trash_collections tc ON u.user_id = tc.user_id " +
                                          "WHERE u.role != 'leader'")) {

        while (rs.next()) {
            Object[] row = new Object[4];
            row[0] = rs.getString("username");  // Username
            row[1] = rs.getDate("collection_date");  // Collection date (can be null)
            row[2] = rs.getDouble("total_weight");  // Total weight (can be null or 0)
            row[3] = (row[2] == null) ? 0.0 : row[2];  // Ensure non-null total weight
            model.addRow(row);
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

    private void loadLeaderboard() {
    String query = "SELECT username, total_collected FROM leaderboard_view ORDER BY total_collected DESC";

    try (Connection conn = DatabaseConnection.connect();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(query)) {

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);

        int rank = 1;
        while (rs.next()) {
            String username = rs.getString("username");
            double totalCollected = rs.getDouble("total_collected");

            // Add a row with rank, username, and total collected value
            model.addRow(new Object[] { rank, username, totalCollected });

            rank++; // Increment rank for next row
        }

    } catch (SQLException e) {
        e.printStackTrace();
    }
}

    public void calculateTotalTrashCollected() {
        try (Connection con = DatabaseConnection.connect();
             Statement stmt = con.createStatement();
             // SQL query to sum the total weight from trash_details
             ResultSet rs = stmt.executeQuery("SELECT SUM(td.weight) AS total_trash FROM trash_details td")) {

            if (rs.next()) {
                double totalTrash = rs.getDouble("total_trash");
                TotalTrashTextField.setText(String.valueOf(totalTrash));  // Display total trash in text field
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }



    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TotalTrashTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TrashCollectedTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel1.setText("LEADERBOARD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel2.setText("SHIBUYA TRASH COLLECTOR'S");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        TotalTrashTextField.setEditable(false);
        TotalTrashTextField.setBackground(new java.awt.Color(0, 153, 153));
        TotalTrashTextField.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jPanel1.add(TotalTrashTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 37, 120, 30));

        TrashCollectedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Members", "Collection Date", "Trash Collected", "Total Weight"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TrashCollectedTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 380, 180));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel3.setText("TOTAL TRASH COLLECTED:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Rank", "Most Trash Collected", "Total Weight"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 380, 180));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel4.setText("MEMBERS TRASH COLLECTED");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        LogoutButton.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        this.dispose();
        LoginTrash loginWindow = new LoginTrash();
        loginWindow.setVisible(true);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leader_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leader_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leader_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leader_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leader_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutButton;
    private javax.swing.JTextField TotalTrashTextField;
    private javax.swing.JTable TrashCollectedTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
